"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var VendingMachine_1 = require("./VendingMachine");
var Product_1 = require("./Product");
var Coin_1 = require("./Coin");
var CoinType_1 = require("./CoinType");
var vendingMachine = VendingMachine_1.default.getInstance();
var coke = new Product_1.default('Coke', 25);
var pepsi = new Product_1.default('Pepsi', 30);
var maaza = new Product_1.default('Maaza', 35);
var water = new Product_1.default('Water', 20);
vendingMachine.inventory.addProduct(coke, 10);
vendingMachine.inventory.addProduct(pepsi, 10);
vendingMachine.inventory.addProduct(maaza, 10);
vendingMachine.inventory.addProduct(water, 10);
console.log('\n ------------- Selecting product Coke\n');
vendingMachine.selectProduct(coke);
vendingMachine.insertCoin(new Coin_1.default(CoinType_1.default.DIME));
vendingMachine.insertCoin(new Coin_1.default(CoinType_1.default.QUARTER));
vendingMachine.dispenseProduct();
vendingMachine.returnChange();
console.log('\n ------------- Selecting product Pepsi\n');
vendingMachine.selectProduct(pepsi);
vendingMachine.insertCoin(new Coin_1.default(CoinType_1.default.QUARTER));
vendingMachine.insertCoin(new Coin_1.default(CoinType_1.default.QUARTER));
vendingMachine.dispenseProduct();
vendingMachine.returnChange();
