"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var SingleRoom_1 = require("./Rooms/SingleRoom");
var DoubleRoom_1 = require("./Rooms/DoubleRoom");
var DeluxeRoom_1 = require("./Rooms/DeluxeRoom");
var RoomMaintenenceVisitor_1 = require("./RoomMaintenenceVisitor");
var RoomPricingVisitor_1 = require("./RoomPricingVisitor");
var singleRoom = new SingleRoom_1.default();
var doubleRoom = new DoubleRoom_1.default();
var deluxeRoom = new DeluxeRoom_1.default();
var pricingRoomVisitor = new RoomPricingVisitor_1.default();
singleRoom.accept(pricingRoomVisitor);
doubleRoom.accept(pricingRoomVisitor);
deluxeRoom.accept(pricingRoomVisitor);
console.log(singleRoom.roomPrice);
console.log(doubleRoom.roomPrice);
console.log(deluxeRoom.roomPrice);
var roomMaintenenceVisitor = new RoomMaintenenceVisitor_1.default();
singleRoom.accept(roomMaintenenceVisitor);
doubleRoom.accept(roomMaintenenceVisitor);
deluxeRoom.accept(roomMaintenenceVisitor);
