"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Context_1 = require("./Context");
var SumNonTerminalExpression_1 = require("./SumNonTerminalExpression");
var MultiplyNonTerminalExpression_1 = require("./MultiplyNonTerminalExpression");
var NumberTerminalExpression_1 = require("./NumberTerminalExpression");
var BinaryNonTerminalExpression_1 = require("./BinaryNonTerminalExpression");
var context = new Context_1.default();
context.put("a", 5);
context.put("b", 10);
context.put("c", 15);
context.put("d", 20);
var mulExpression = new MultiplyNonTerminalExpression_1.default(new NumberTerminalExpression_1.default("a"), new NumberTerminalExpression_1.default("b"));
console.log(mulExpression.interpret(context));
console.log("\n");
var sumExpression = new SumNonTerminalExpression_1.default(new NumberTerminalExpression_1.default("c"), new NumberTerminalExpression_1.default("d"));
console.log(sumExpression.interpret(context));
console.log("\n");
var complexExpression = new SumNonTerminalExpression_1.default(mulExpression, sumExpression);
console.log(complexExpression.interpret(context));
console.log("\n");
var binaryExp = new BinaryNonTerminalExpression_1.default(mulExpression, sumExpression, "+");
console.log(binaryExp.interpret(context));
