"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const StackOverflow_1 = __importDefault(require("./StackOverflow"));
const system = new StackOverflow_1.default();
const alice = system.createUser("Alice", "abc@xyz");
const bob = system.createUser("Bob", "def@xyz");
const charlie = system.createUser("Charlie", "ghi@xyz");
const javaQuestion = system.askQuestion("Java", "What is Java?", alice, ["Java", "OOP"]);
const bonAnswer = system.answerQuestion(javaQuestion, "Java is a programming language", bob);
system.addComment(bonAnswer, "This is a good answer", charlie);
system.addComment(bonAnswer, "This is a bad answer", alice);
system.voteQuestion(bob, javaQuestion, 1);
system.voteAnswer(charlie, bonAnswer, 1);
system.acceptAnswer(bonAnswer);
const javaScriptQuestion = system.askQuestion("JavaScript", "What is JavaScript?", bob, ["JavaScript", "Web"]);
const aliveAnswer = system.answerQuestion(javaScriptQuestion, "JavaScript is a programming language", alice);
system.addComment(aliveAnswer, "This is a good answer", charlie);
system.voteAnswer(alice, aliveAnswer, 1);
system.voteQuestion(charlie, javaScriptQuestion, 1);
console.log("\u001B[95m" /* ConsoleColors.fgBrightMagenta */ + "Question " + javaQuestion.getTitle() + "\u001B[0m" /* ConsoleColors.reset */);
console.log("\u001B[36m" /* ConsoleColors.fgCyan */ + "Content " + javaQuestion.getContent() + "\u001B[0m" /* ConsoleColors.reset */);
console.log("\u001B[33m" /* ConsoleColors.fgYellow */ + "Asked by " + javaQuestion.getAuthor().getUsername() + "\u001B[0m" /* ConsoleColors.reset */);
console.log("\u001B[32m" /* ConsoleColors.fgGreen */ + "Votes " + javaQuestion.getVoteCount() + "\u001B[0m" /* ConsoleColors.reset */);
console.log("\u001B[34m" /* ConsoleColors.fgBlue */ + "Comments " + javaQuestion.getComments().length + "\u001B[0m" /* ConsoleColors.reset */);
console.log("\u001B[35m" /* ConsoleColors.fgMagenta */ + "Tags " + javaQuestion.getTags().map(tag => tag.getName()).join(", ") + "\u001B[0m" /* ConsoleColors.reset */);
console.log("\u001B[96m" /* ConsoleColors.fgBrightCyan */ + "Answer " + bonAnswer.getContent() + "\u001B[0m" /* ConsoleColors.reset */);
console.log("\u001B[33m" /* ConsoleColors.fgYellow */ + "Answered by " + bonAnswer.getAuthor().getUsername() + "\u001B[0m" /* ConsoleColors.reset */);
console.log("\u001B[32m" /* ConsoleColors.fgGreen */ + "Votes " + bonAnswer.getVoteCount() + "\u001B[0m" /* ConsoleColors.reset */);
console.log("\u001B[34m" /* ConsoleColors.fgBlue */ + "Comments " + bonAnswer.getComments().length + "\u001B[0m" /* ConsoleColors.reset */);
console.log("\u001B[97m" /* ConsoleColors.fgBrightWhite */ + "User reputation" + "\u001B[0m" /* ConsoleColors.reset */);
console.log("\u001B[91m" /* ConsoleColors.fgBrightRed */ + alice.getUsername() + " " + alice.getReputation() + "\u001B[0m" /* ConsoleColors.reset */);
console.log("\u001B[92m" /* ConsoleColors.fgBrightGreen */ + bob.getUsername() + " " + bob.getReputation() + "\u001B[0m" /* ConsoleColors.reset */);
console.log("\u001B[94m" /* ConsoleColors.fgBrightBlue */ + charlie.getUsername() + " " + charlie.getReputation() + "\u001B[0m" /* ConsoleColors.reset */);
console.log("\u001B[95m" /* ConsoleColors.fgBrightMagenta */ + "Search results for Java" + "\u001B[0m" /* ConsoleColors.reset */);
const results = system.searchQuestions("Java");
results.forEach(question => {
    console.log("\u001B[36m" /* ConsoleColors.fgCyan */ + " => " + question.getContent() + "\u001B[0m" /* ConsoleColors.reset */);
});
