"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Level_1 = require("./Level");
var ParkingLot_1 = require("./ParkingLot");
var Car_1 = require("./Models/Car");
var Motorbike_1 = require("./Models/Motorbike");
var Truck_1 = require("./Models/Truck");
var parkingLotInstance = ParkingLot_1.default.getInstance();
parkingLotInstance.addLevel(new Level_1.default(1, 10));
parkingLotInstance.addLevel(new Level_1.default(2, 10));
var car1 = new Car_1.default("1234");
var bike1 = new Motorbike_1.default("2345");
var truck1 = new Truck_1.default("3456");
parkingLotInstance.parkVehicle(car1);
parkingLotInstance.parkVehicle(truck1);
parkingLotInstance.parkVehicle(bike1);
parkingLotInstance.displayAvailability();
parkingLotInstance.unparkVehicle(car1);
parkingLotInstance.unparkVehicle(truck1);
parkingLotInstance.displayAvailability();
